pod 'GoogleSignIn', :path => '../../../', :testspecs => ['unit']
pod 'GoogleSignInSwift', :path => '../../../'
project 'DaysUntilBirthdayForPod.xcodeproj'

target 'DaysUntilBirthdayForPod(iOS)' do
  platform :ios, '13.0'
end

target 'DaysUntilBirthdayForPod(macOS)' do
  platform :osx, '10.15'
end
