pod 'GoogleSignIn', :path => '../../../', :testspecs => ['unit']
pod 'GoogleSignInSwiftSupport', :path => '../../../', :testspecs => ['unit']
project 'AppAttestExample.xcodeproj'

use_frameworks! :linkage => :static

target 'AppAttestExample' do
  pod 'AppCheckCore', :git => 'https://github.com/google/app-check.git', :tag => 'CocoaPods-0.1.0-alpha.4'
  platform :ios, '14.0'
end
