name: Build GSI for Valid Architectures	

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Cron uses UTC; run at nightly at midnight PST

jobs:
  cron:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
  
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    - name: Archive for iOS
      run: |
        xcodebuild \
          archive \
          -scheme GoogleSignIn-Package \
          -destination "generic/platform=iOS"
    - name: Archive for macOS
      run: |
        xcodebuild \
          archive \
          -scheme GoogleSignIn-Package \
          -destination "platform=OS X"
