name: GSI Chatroom PR Notification

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Details
        run: |
          echo "Pull Request: ${{ github.event.pull_request.number }}"
          echo "Author: ${GITHUB_EVENT_PULL_REQUEST_USER_LOGIN}"
        env:
          GITHUB_EVENT_PULL_REQUEST_USER_LOGIN: ${{ github.event.pull_request.user.login }}

      - name: Google Chat Notification
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          TITLE: ${{ github.event.pull_request.title }}
          LABELS: ${{ join(github.event.pull_request.labels.*.name, ', ') }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          PAYLOAD=$(jq -n \
            --arg pr_num "$PR_NUMBER" \
            --arg title "$TITLE" \
            --arg labels "$LABELS" \
            --arg url "$URL" \
            '{
              cardsV2: [
                {
                  cardId: "prNotificationCard",
                  card: {
                    header: {
                      title: "Pull request notification",
                      subtitle: ("Pull request: #" + $pr_num)
                    },
                    sections: [
                      {
                        widgets: [
                          {
                            decoratedText: {
                              topLabel: "Title",
                              text: $title
                            }
                          },
                          {
                            decoratedText: {
                              topLabel: "Labels",
                              text: (if $labels != "" then $labels else "None" end)
                            }
                          },
                          {
                            buttonList: {
                              buttons: [
                                {
                                  text: "Open Pull Request",
                                  onClick: {
                                    openLink: {
                                      url: $url
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }')

          curl --location --request POST '${{ secrets.WEBHOOK_URL }}' \
            --header 'Content-Type: application/json; charset=UTF-8' \
            --data "$PAYLOAD"
